const CLIENT_DOMAIN = 'http://localhost:3000/'
 const ADMIN_VERIFY_EMAIL_REDIRECT_ROUTE = CLIENT_DOMAIN+'admin/verify-email' 
 const ADMIN_CLIENT_DASHBOARD_ROUTE = CLIENT_DOMAIN+'admin/dashboard'
 const ADMIN_CLIENT_CHANGE_PASSWORD_ROUTE = CLIENT_DOMAIN +'admin/change-password'
 const EMAIL_VERIFICATION_ERROR_ROUTE = CLIENT_DOMAIN + '/email-verification-error'

 module.exports={ADMIN_VERIFY_EMAIL_REDIRECT_ROUTE,ADMIN_CLIENT_DASHBOARD_ROUTE,ADMIN_CLIENT_CHANGE_PASSWORD_ROUTE,EMAIL_VERIFICATION_ERROR_ROUTE}
